@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "tqs.electro.electro.endToEnd.steps.MapSteps",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1663120372 { 
   	label=electro
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1579361238 { 
   	label=electro
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   MapSteps1811192358[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MapSteps</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ bookingModalShouldOpen()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iAmOnMyBookingsPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iAmOnTheHomePage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iAmOnTheLoginPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iAmOnTheRegistrationPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iClickBookThisStation()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iClickOnTheLink(linkId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iClickOnTheLinkInTheNavigationBar(linkText: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iClickPayNow()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iClickTheButton(buttonText: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iConfirmBooking()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iFillBookingDates(start: String, end: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iFillInTheLoginFormWithEmailAndPassword(email: String, password: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iFillInTheRegistrationFormWith(table: DataTable)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iFillInTheStationFormWith(table: DataTable)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iFillPaymentForm(table: DataTable)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSelectFromTheStationDropdown(stationName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSelectStationFromDropdown(stationLabel: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSelectTheStationOnTheMap(name: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldBeOnTheLoginPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldBeOnTheMapPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldBeOnTheRegisterPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldBeRedirectedToTheLoginPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldSeeBookingSuccess(msg: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldSeePaymentSuccessAndStatus(successMsg: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldSeeSuccessAndRedirectToLogin(successMessage: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ iShouldSeeTheMapRecenterToLatitudeAndLongitude()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSubmitPayment()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSubmitTheLoginForm()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSubmitTheNewStationForm()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iSubmitTheRegistrationForm()</TD></TR>
<TR><TD ALIGN="LEFT" >+ iWaitUntilTheStationListContains(stationName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ paymentModalShouldOpen()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tearDown()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml