version: '3.8'

services:
  dbtest:
    image: postgres:13
    environment:
      POSTGRES_DB: ElectroTest
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  backendtest:
    build: ./backend/
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.application.name": "backend",
          "spring.datasource.url": "jdbc:postgresql://dbtest:5432/ElectroTest",
          "spring.datasource.username": "${DB_USER}",
          "spring.datasource.password": "${DB_PASS}",
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",

          "management.endpoints.web.exposure.include": "health,prometheus,metrics",
          "management.endpoints.web.base-path": "/actuator",
          "management.endpoint.health.show-details": "never"
        }'
    ports:
      - "8081:8080"
    depends_on:
      - dbtest

  frontendtest:
    build: ./frontend/
    ports:
      - "3333:3000"  
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=/backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backendtest

  proxytest:
    depends_on:
      - backendtest
      - frontendtest
    image: nginx:1.27-alpine
    volumes:
      - "./nginx_test.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8000:80"

  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
    depends_on:
      - backendtest
      - frontendtest

volumes:
  postgres_data_test:
    driver: local
